### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "firstname" : "Loc",
    "lastname" : "Ngo",
    "email" : "locnht1@gmail.com",
    "password" : "12345",
    "role" : "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token); %}

### Create a new book
POST http://localhost:8080/api/v1/books
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "author" : "Loc",
    "isbn"" : "12345"
}

### Update one book
POST http://localhost:8080/api/v1/books
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "id" : 1,
    "author" : "Loc",
    "isbn"" : "12345"
}

### Query the Books one more time
GET http://localhost:8080/api/v1/books
Authorization: Bearer {{auth-token}}